## Munkres / Hungarian algorithm

In [2]:
from scipy.spatial import distance
from munkres import munkres
import numpy as np

In [3]:
frame1 = [(0, 0), (3, 4)]
frame2 = [(3, 4), (0, 0)]

distance_matrix = distance.cdist(frame1, frame2)
print(distance_matrix)
assignment = munkres(distance_matrix)
print(assignment)
cost = distance_matrix[assignment].sum()
print(cost)

[[5. 0.]
 [0. 5.]]
[[False  True]
 [ True False]]
0.0


In [4]:
def calculate_distance(X, Y):
    distance_matrix = distance.cdist(X, Y)
    assignment = munkres(distance_matrix)
    return distance_matrix[assignment].sum()


In [5]:
%%timeit
calculate_distance(frame1, frame2)

45 µs ± 706 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
frame1 = np.random.rand(11, 2)
frame2 = frame1.copy()
np.random.shuffle(frame2)
movement = np.random.rand(11, 2) / 100
frame2 += movement
frame2, frame1


(array([[0.9260427 , 0.60921874],
        [0.19061324, 0.91909264],
        [0.34878056, 0.25297231],
        [0.13797586, 0.6992336 ],
        [0.20976302, 0.45666601],
        [0.30008269, 0.55558341],
        [0.45975815, 0.18384112],
        [0.33977761, 0.04467445],
        [0.09613069, 0.81204136],
        [0.83261651, 0.46246813],
        [0.97344475, 0.89240573]]),
 array([[0.18152087, 0.9178373 ],
        [0.9192994 , 0.60805294],
        [0.83248104, 0.45687527],
        [0.34391421, 0.2518138 ],
        [0.29692226, 0.54960835],
        [0.13261502, 0.69809946],
        [0.33677253, 0.04292371],
        [0.20307903, 0.44902641],
        [0.44986469, 0.17421359],
        [0.08880301, 0.8112658 ],
        [0.96818604, 0.88994553]]))

In [7]:
distance_matrix = distance.cdist(frame1, frame2)
distance_matrix

array([[0.80595172, 0.00917862, 0.68558097, 0.22289851, 0.46203526,
        0.38116241, 0.78496267, 0.88738862, 0.13595685, 0.79453547,
        0.79233212],
       [0.00684332, 0.79229365, 0.67199257, 0.78662595, 0.72550664,
        0.62143575, 0.62540693, 0.80823316, 0.84806721, 0.1694369 ,
        0.28946197],
       [0.17878008, 0.79097356, 0.52492149, 0.735578  , 0.62271806,
        0.54147142, 0.46202814, 0.64239099, 0.81752968, 0.0055945 ,
        0.45777457],
       [0.68308993, 0.68466213, 0.00500235, 0.49253942, 0.24486929,
        0.30691559, 0.13431346, 0.20718065, 0.61257781, 0.53217025,
        0.89814627],
       [0.63193823, 0.38447399, 0.3011349 , 0.21829263, 0.12741669,
        0.00675941, 0.40037632, 0.50674928, 0.33043658, 0.54273543,
        0.75841461],
       [0.79839042, 0.22847709, 0.49483909, 0.0054795 , 0.25345991,
        0.21990053, 0.6094951 , 0.68547836, 0.11964055, 0.73859611,
        0.86298874],
       [0.81726947, 0.88827616, 0.21039155, 0.68575709, 0.

In [8]:
assignment = munkres(distance_matrix)
assignment

array([[False,  True, False, False, False, False, False, False, False,
        False, False],
       [ True, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
         True, False],
       [False, False,  True, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False],
       [False, False, False,  True, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False,  True, False,
        False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False],
       [False, False, False, False, False, False,  True, False, False,
        False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False],
       [False, False, False, False, False, False, False, Fal

In [9]:
distance_matrix[assignment]

array([0.00917862, 0.00684332, 0.0055945 , 0.00500235, 0.00675941,
       0.0054795 , 0.00347787, 0.01015082, 0.0138047 , 0.00736861,
       0.00580574])

In [10]:
distance_matrix[assignment].sum()

0.07946544260169368

In [11]:
((movement[:, 0] ** 2 + movement[:, 1] ** 2) ** 0.5).sum()

0.07946544260169366

In [12]:
%%timeit
calculate_distance(frame1, frame2)

37.7 µs ± 793 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
